# Generated by Django 5.2.8 on 2025-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accent_gradient',
            field=models.CharField(blank=True, help_text='Tailwind CSS gradient classes for product accent colors', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Hero tagline displayed on product pages', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='Array of note strings'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefit strings'),
        ),
    ]
