"""
Django settings for myura_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Try python-decouple first (already in requirements), fallback to manual .env reading
try:
    from decouple import config
    USE_DECOUPLE = True
    # decouple automatically loads .env file from BASE_DIR
except ImportError:
    USE_DECOUPLE = False
    # Fallback: manually load .env file
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()
        print(f"[Settings] Loaded .env file from {env_path}")
    else:
        print(f"[Settings] Warning: .env file not found at {env_path}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+%-&7$gvk0^=(rls40q&h8m+=*mlbnddpg&kyw@4dps&fcf#3m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    
    # Local apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.EnsureSessionMiddleware',  # Custom middleware to ensure session is saved
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myura_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myura_backend.wsgi.application'

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True
# For localhost development, use 'Lax' which works with Secure=False
SESSION_COOKIE_SAMESITE = 'Lax'  # 'Lax' works well for same-origin requests (localhost)
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_DOMAIN = None  # None means current domain (localhost works)
SESSION_COOKIE_PATH = '/'  # Cookie available for all paths


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Allow custom headers for cart ID fallback mechanism
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-cart-id',  # Custom header for cart ID fallback
    'x-csrf-token',
    'x-requested-with',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Media files (for uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration
# For development: emails are printed to console
# For production: configure SMTP settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@myurawellness.com'

# Production SMTP settings (uncomment and configure for production)
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# PhonePe Payment Gateway Settings
if USE_DECOUPLE:
    # Use decouple if available (better .env handling)
    PHONEPE_CLIENT_ID = config('PHONEPE_CLIENT_ID', default='')
    PHONEPE_CLIENT_SECRET = config('PHONEPE_CLIENT_SECRET', default='')
    PHONEPE_MERCHANT_ID = config('PHONEPE_MERCHANT_ID', default='')
    PHONEPE_API_URL = config('PHONEPE_API_URL', default='https://api-preprod.phonepe.com/apis/pg-sandbox')
    PHONEPE_REDIRECT_URL = config('PHONEPE_REDIRECT_URL', default='http://localhost:3000/payment/success')
    PHONEPE_CALLBACK_URL = config('PHONEPE_CALLBACK_URL', default='http://127.0.0.1:8000/api/payments/phonepe/callback')
else:
    # Fallback to os.getenv (after manual .env loading)
    PHONEPE_CLIENT_ID = os.getenv('PHONEPE_CLIENT_ID', '')
    PHONEPE_CLIENT_SECRET = os.getenv('PHONEPE_CLIENT_SECRET', '')
    PHONEPE_MERCHANT_ID = os.getenv('PHONEPE_MERCHANT_ID', '')
    PHONEPE_API_URL = os.getenv('PHONEPE_API_URL', 'https://api-preprod.phonepe.com/apis/pg-sandbox')
    PHONEPE_REDIRECT_URL = os.getenv('PHONEPE_REDIRECT_URL', 'http://localhost:3000/payment/success')
    PHONEPE_CALLBACK_URL = os.getenv('PHONEPE_CALLBACK_URL', 'http://127.0.0.1:8000/api/payments/phonepe/callback')

# Debug: Print if credentials are loaded (remove in production)
if not PHONEPE_CLIENT_ID:
    print("[Settings] WARNING: PHONEPE_CLIENT_ID is empty. Check .env file.")
else:
    print(f"[Settings] PhonePe Client ID loaded: {PHONEPE_CLIENT_ID[:20]}...")

# Cashfree Payment Gateway Settings
if USE_DECOUPLE:
    CASHFREE_APP_ID = config('CASHFREE_APP_ID', default='')
    CASHFREE_SECRET_KEY = config('CASHFREE_SECRET_KEY', default='')
    CASHFREE_API_URL = config('CASHFREE_API_URL', default='https://sandbox.cashfree.com/pg')
    CASHFREE_REDIRECT_URL = config('CASHFREE_REDIRECT_URL', default='http://localhost:3000/payment/success')
    CASHFREE_CALLBACK_URL = config('CASHFREE_CALLBACK_URL', default='http://127.0.0.1:8000/api/payments/cashfree/callback')
else:
    CASHFREE_APP_ID = os.getenv('CASHFREE_APP_ID', '')
    CASHFREE_SECRET_KEY = os.getenv('CASHFREE_SECRET_KEY', '')
    CASHFREE_API_URL = os.getenv('CASHFREE_API_URL', 'https://sandbox.cashfree.com/pg')
    CASHFREE_REDIRECT_URL = os.getenv('CASHFREE_REDIRECT_URL', 'http://localhost:3000/payment/success')
    CASHFREE_CALLBACK_URL = os.getenv('CASHFREE_CALLBACK_URL', 'http://127.0.0.1:8000/api/payments/cashfree/callback')
